package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.68

import (
	"context"
	"task/internal/api/graphql/graph/model"
)

// BestMaterial is the resolver for the bestMaterial field.
func (r *queryResolver) BestMaterial(ctx context.Context, materialType string, price float64, locality string) ([]*model.BestMaterial, error) {
	return r.Svc.FindBestMaterial(materialType, price, locality)

}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *queryResolver) Materials(ctx context.Context) ([]*model.Material, error) {
	panic(fmt.Errorf("not implemented: Materials - materials"))
}
*/
