// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type BestMaterial struct {
	Material *Material `json:"material"`
	Supplier *Supplier `json:"supplier"`
}

type Material struct {
	ID           int32   `json:"id"`
	MaterialName string  `json:"materialName"`
	MaterialType string  `json:"materialType"`
	Price        float64 `json:"price"`
	Unit         string  `json:"unit"`
	Rating       int32   `json:"rating"`
	Quality      int32   `json:"quality"`
}

type Query struct {
}

type Supplier struct {
	ID                int32  `json:"id"`
	SupplierName      string `json:"supplierName"`
	SupplierLocation  string `json:"supplierLocation"`
	StockAvailability string `json:"stockAvailability"`
	StockQuantity     int32  `json:"stockQuantity"`
}
